from pathlib import Path

from .schema import EnrichedTemplate

HEADER = """\
# Meme template catalog — generated by meme-seeder
# Format: INI-style, one section per template
# Compatible with you-get-a-meme's configparser loader
#
# Fields:
#   name           — display name
#   description    — semantic description for embedding search
#   caption_pattern — instructions for LLM caption generation
#   box_labels     — comma-separated labels, one per text box (in order)
#   tags           — comma-separated keywords
#   box_count      — number of text boxes in the template image
#   image_url      — Imgflip source image
#   tone           — dominant register (humorous, ironic, sarcastic, ...)
#   notes          — caption-writer guidance: baked-in text, blank panels, common misuse
"""


def write_templates(templates: list[EnrichedTemplate], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sections = [HEADER] + [t.to_ini_section() for t in sorted(templates, key=lambda t: t.name.lower())]
    output_path.write_text("\n\n".join(sections) + "\n")
